export const phase10Ids = {
  application: crypto.randomUUID(),
  articleStep: crypto.randomUUID(),
  coachEntitlement: crypto.randomUUID(),
  coachPayment: crypto.randomUUID(),
  dailyStep: crypto.randomUUID(),
  day: crypto.randomUUID(),
  destination: crypto.randomUUID(),
  finalStep: crypto.randomUUID(),
  formQuestion: crypto.randomUUID(),
  formStep: crypto.randomUUID(),
  initialStep: crypto.randomUUID(),
  optionCorrect: crypto.randomUUID(),
  optionWrong: crypto.randomUUID(),
  photoQuestion: crypto.randomUUID(),
  program: crypto.randomUUID(),
  quizQuestion: crypto.randomUUID(),
  quizStep: crypto.randomUUID(),
} as const;

export const phase10CoachQr = `phase10_browser_${crypto.randomUUID().replaceAll("-", "_")}`;

export function buildPhase10ProgramPayload(today: string, tomorrow: string) {
  return {
    days: [
      {
        day_number: 1,
        id: phase10Ids.day,
        scheduled_on: today,
        steps: [
          {
            completion_policy: "submit_weigh_in",
            content_kind: "initial_weigh_in",
            id: phase10Ids.initialStep,
            instructions: "",
            questions: [],
            step_order: 1,
            title: "Timbang awal",
            verification_mode: "automatic",
          },
          {
            completion_policy: "mark_complete",
            content_kind: "article",
            id: phase10Ids.articleStep,
            instructions: "Baca panduan kebiasaan sehat.",
            questions: [],
            step_order: 2,
            title: "Panduan kebiasaan",
            verification_mode: "automatic",
          },
          {
            completion_policy: "answer_all_questions",
            content_kind: "form",
            id: phase10Ids.formStep,
            instructions: "Jawab refleksi singkat.",
            questions: [
              {
                id: phase10Ids.formQuestion,
                kind: "short_answer",
                options: [],
                prompt: "Apa fokusmu hari ini?",
                question_order: 1,
              },
              {
                id: phase10Ids.photoQuestion,
                kind: "photo_upload",
                options: [],
                prompt: "Unggah bukti aktivitas",
                question_order: 2,
              },
            ],
            step_order: 3,
            title: "Refleksi untuk Coach",
            verification_mode: "coach_review",
          },
          {
            completion_policy: "automatic_quiz",
            content_kind: "quiz",
            id: phase10Ids.quizStep,
            instructions: "Pilih jawaban yang tepat.",
            questions: [
              {
                answer_key: {
                  accepted_text_values: [],
                  matching_mode: "exact",
                  selected_option_ids: [phase10Ids.optionCorrect],
                },
                id: phase10Ids.quizQuestion,
                kind: "single_choice",
                options: [
                  {
                    id: phase10Ids.optionCorrect,
                    option_order: 1,
                    title: "Konsisten dan bertahap",
                  },
                  {
                    id: phase10Ids.optionWrong,
                    option_order: 2,
                    title: "Semua sekaligus",
                  },
                ],
                prompt: "Pendekatan mana yang disarankan?",
                question_order: 1,
              },
            ],
            step_order: 4,
            title: "Kuis kebiasaan",
            verification_mode: "automatic",
          },
          {
            completion_policy: "submit_weigh_in",
            content_kind: "daily_weigh_in",
            id: phase10Ids.dailyStep,
            instructions: "",
            questions: [],
            step_order: 5,
            title: "Timbang harian",
            verification_mode: "automatic",
          },
          {
            completion_policy: "submit_weigh_in",
            content_kind: "final_weigh_in",
            id: phase10Ids.finalStep,
            instructions: "",
            questions: [],
            step_order: 6,
            title: "Timbang akhir",
            verification_mode: "automatic",
          },
        ],
        title: "Hari perjalanan lengkap",
      },
    ],
    desired_price: 150000,
    duration_mode: "fixed_duration",
    ends_on: tomorrow,
    future_step_policy: "locked",
    id: phase10Ids.program,
    pace: "scheduled",
    participant_limit: 5,
    past_step_policy: "available",
    points_per_activity: 10,
    points_per_weight_kg: 100,
    pricing_mode: "paid",
    quiz_passing_percentage: 70,
    registration_closes_at: new Date(Date.now() + 86_400_000).toISOString(),
    starts_on: today,
    summary: "Journey lintas role authoritative.",
    timezone: "Asia/Makassar",
    title: "Program Cross-role Phase 10",
    wellness_disclaimer: "Program kebugaran non-diagnostik.",
  } as const;
}
