import { router } from 'expo-router';
import { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import { AdminCoachApplications } from '@/features/coach/AdminCoachApplicationComponents';
import { numberFormatter } from '@/shared/design/formatters';
import { componentTokens, primitiveTokens, typographyTokens } from '@/shared/design/tokens';
import { useAppTheme } from '@/shared/design/useAppTheme';
import { MSCIcon } from '@/shared/icons/MSCIcon';
import { Button, Card, Field, InlineMessage, ProgressBar, SegmentedControl, StateView, StatusBadge, UserAvatar } from '@/shared/ui/primitives';
import type { AdminPerson } from './admin-models';
import { useAdminMutation, useAdminPeople, useAdminPerson, useAdminPersonOperations, useAdminPrograms } from './admin-queries';

type PeopleScope = 'participant' | 'coach' | 'admin';
type CoachSurface = 'directory' | 'applications';

export function AdminPeopleExperience({ authorized, initialScope = 'participant', pendingOnly = false }: { authorized: boolean; initialScope?: string; pendingOnly?: boolean }) {
  const { colors } = useAppTheme(); const people = useAdminPeople(authorized); const [scope, setScope] = useState<PeopleScope>(isPeopleScope(initialScope) ? initialScope : 'participant'); const [coachSurface, setCoachSurface] = useState<CoachSurface>(pendingOnly ? 'applications' : 'directory'); const [search, setSearch] = useState('');
  if (!authorized) return <StateView kind="forbidden" />;
  if (people.isPending) return <StateView kind="loading" />;
  if (people.isError) return <StateView kind="error" action={<Button label="Coba lagi" onPress={() => void people.refetch()} />} />;
  const visible = (people.data ?? []).filter((person) => person.role === scope && `${person.display_name} ${person.city ?? ''} ${person.email ?? ''}`.toLocaleLowerCase('id-ID').includes(search.trim().toLocaleLowerCase('id-ID')));
  const showDirectory = scope !== 'coach' || coachSurface === 'directory';
  return <View style={styles.fixedScreen} testID="admin.people"><View style={[styles.fixedControls, { backgroundColor: colors.background, borderColor: colors.border }]}><SegmentedControl label="Peran orang" value={scope} onChange={setScope} options={[{ label: 'Peserta', value: 'participant' }, { label: 'Coach', value: 'coach' }, { label: 'Admin', value: 'admin' }]} />{scope === 'coach' ? <SegmentedControl label="Tampilan Coach" value={coachSurface} onChange={setCoachSurface} options={[{ label: 'Daftar Coach', value: 'directory' }, { label: 'Aplikasi Coach', value: 'applications' }]} /> : null}{showDirectory ? <View style={[styles.searchField, { borderColor: colors.border, backgroundColor: colors.surface }]}><MSCIcon name="search" color={colors.secondaryText} /><TextInput accessibilityLabel="Cari nama atau kota" value={search} onChangeText={setSearch} placeholder="Cari nama atau kota" placeholderTextColor={colors.secondaryText} style={[styles.searchInput, { color: colors.primaryText }]} /></View> : null}</View><ScrollView contentContainerStyle={styles.peopleList}>
    {scope === 'coach' && coachSurface === 'applications' ? <AdminCoachApplications authorized={authorized} /> : <><Text accessibilityRole="header" style={[styles.sectionTitle, { color: colors.primaryText }]}>{scope === 'participant' ? 'Peserta' : scope === 'coach' ? 'Coach' : 'Admin'}</Text>{visible.length === 0 ? <StateView kind="empty" /> : <Card>{visible.map((person, index) => <PersonRow key={person.user_id} person={person} border={index > 0} />)}</Card>}</>}
  </ScrollView></View>;
}

function PersonRow({ person, border }: { person: AdminPerson; border: boolean }) {
  const { colors } = useAppTheme();
  return <Pressable accessibilityRole="link" accessibilityLabel={`${person.display_name}, ${person.city ?? person.role}`} onPress={() => router.push(`/admin/people/${person.user_id}` as never)} testID={`admin.people.open.${person.user_id}`} style={({ pressed }) => [styles.personRow, border && { borderColor: colors.border }, { opacity: pressed ? 0.72 : 1 }]}><UserAvatar uri={person.provider_avatar_url ?? undefined} label={person.display_name} size={50} /><View style={styles.flex}><View style={styles.inlineWrap}><Text style={[styles.bodyStrong, { color: colors.primaryText }]}>{person.display_name}</Text>{person.application_status && ['submitted', 'pending_admin_approval'].includes(person.application_status) ? <StatusBadge label="Perlu persetujuan" tone="warning" /> : null}</View><Text style={[styles.caption, { color: colors.secondaryText }]}>{person.city || person.email || roleLabel(person.role)}</Text></View><MSCIcon name="chevron" color={colors.secondaryText} /></Pressable>;
}

export function AdminPersonDetailExperience({ authorized, personId }: { authorized: boolean; personId: string }) {
  const { colors } = useAppTheme(); const personQuery = useAdminPerson(personId, authorized); const people = useAdminPeople(authorized); const programs = useAdminPrograms(authorized); const operations = useAdminPersonOperations(personId, authorized); const mutation = useAdminMutation();
  const [programId, setProgramId] = useState(''); const [coachId, setCoachId] = useState('');
  const [enrollmentReason, setEnrollmentReason] = useState(''); const [coachReason, setCoachReason] = useState(''); const [scoreReason, setScoreReason] = useState('');
  const [adjustment, setAdjustment] = useState(''); const [selectedEnrollment, setSelectedEnrollment] = useState('');
  const person = personQuery.data;
  const coaches = useMemo(() => (people.data ?? []).filter((candidate) => candidate.role === 'coach' && candidate.coach_is_approved), [people.data]);
  const availablePrograms = useMemo(() => (programs.data ?? []).filter((program) => ['scheduled', 'active'].includes(program.status)), [programs.data]);
  if (!authorized) return <StateView kind="forbidden" />;
  if (personQuery.isPending || people.isPending || programs.isPending || operations.isPending) return <StateView kind="loading" />;
  if (personQuery.isError || people.isError || programs.isError || operations.isError) return <StateView kind="error" action={<Button label="Coba lagi" onPress={() => void Promise.all([personQuery.refetch(), people.refetch(), programs.refetch(), operations.refetch()])} />} />;
  if (!person) return <StateView kind="empty" action={<Button label="Kembali ke Orang" onPress={() => router.replace('/admin/people')} />} />;
  const execute = async (command: Parameters<typeof mutation.mutateAsync>[0]) => { await mutation.mutateAsync(command); setEnrollmentReason(''); setCoachReason(''); setScoreReason(''); setAdjustment(''); await operations.refetch(); };
  return <ScrollView contentContainerStyle={styles.detailContent} testID="admin.people.detail"><Button label="Kembali ke Orang" icon="back" tone="secondary" onPress={() => router.back()} /><Text accessibilityRole="header" style={[styles.title, { color: colors.primaryText }]}>Profil {roleLabel(person.role)}</Text><Card><View style={styles.identity}><UserAvatar uri={person.provider_avatar_url ?? undefined} label={person.display_name} size={88} /><View style={styles.flex}><Text style={[styles.title, { color: colors.primaryText }]}>{person.display_name}</Text><Text style={[styles.body, { color: colors.secondaryText }]}>{person.email || 'Email tidak tersedia'}</Text><StatusBadge label={roleLabel(person.role)} tone={person.role === 'coach' && person.coach_is_approved ? 'success' : 'info'} /></View></View></Card>
    <Card><Text accessibilityRole="header" style={[styles.cardTitle, { color: colors.primaryText }]}>Data profil</Text><Detail label="Nama" value={person.display_name} /><Detail label="Nomor HP" value={person.phone_number || 'Belum dicantumkan'} /><Detail label="Kota" value={person.city || 'Belum dicantumkan'} />{person.role === 'participant' ? <Detail label="Coach pendamping" value={person.current_coach_name || 'Belum ditetapkan'} /> : null}{person.role === 'coach' ? <><Detail label="Status Coach" value={person.coach_is_approved ? 'Disetujui' : 'Belum disetujui'} /><Detail label="Profil publik" value={person.profile_published ? `Terbit · /c/${person.public_handle}` : 'Belum diterbitkan'} />{person.coach_biography ? <Detail label="Biografi" value={person.coach_biography} /> : null}</> : null}</Card>
    {person.role === 'participant' ? <><Card><Text accessibilityRole="header" style={[styles.cardTitle, { color: colors.primaryText }]}>Program peserta</Text>{operations.data?.enrollments.length ? operations.data.enrollments.map((enrollment) => <View key={enrollment.id} style={[styles.enrollment, { borderColor: colors.border }]}><View style={styles.rowBetween}><Text style={[styles.bodyStrong, { color: colors.primaryText }]}>{enrollment.program_title}</Text><StatusBadge label={enrollment.status === 'active' ? 'Aktif' : enrollment.status} tone={enrollment.status === 'active' ? 'success' : 'info'} /></View><ProgressBar label="Kemajuan" value={enrollment.progress_percentage / 100} /><Text style={[styles.caption, { color: colors.secondaryText }]}>Aktivitas {numberFormatter.format(enrollment.activity_points)} · Kuis {numberFormatter.format(enrollment.quiz_points)} · Berat {numberFormatter.format(enrollment.weight_points)} · Penyesuaian {numberFormatter.format(enrollment.adjustment_points)}</Text></View>) : <Text style={[styles.body, { color: colors.secondaryText }]}>Belum mengikuti program.</Text>}</Card>
      <Card><Text accessibilityRole="header" style={[styles.cardTitle, { color: colors.primaryText }]}>Pendaftaran manual</Text><Text style={[styles.body, { color: colors.secondaryText }]}>Hanya batas waktu yang dapat dioverride. Kapasitas, Coach, lifecycle, dan pembayaran tetap diperiksa server.</Text><ChoiceList label="Program" options={availablePrograms.map((program) => ({ value: program.id, label: `${program.title} · ${program.registration_closes_at ? 'Deadline ' + formatDateTime(program.registration_closes_at) : 'Tanpa deadline'}` }))} value={programId} onChange={setProgramId} /><Field label="Alasan enrollment" value={enrollmentReason} onChangeText={setEnrollmentReason} /><Button label="Daftarkan peserta" disabled={!programId || enrollmentReason.trim().length < 8} loading={mutation.isPending} onPress={() => void execute({ kind: 'enrollParticipant', participantId: person.user_id, programId, reason: enrollmentReason })} /></Card>
      <Card><Text accessibilityRole="header" style={[styles.cardTitle, { color: colors.primaryText }]}>Perubahan Coach</Text><Text style={[styles.body, { color: colors.secondaryText }]}>Enrollment aktif dan terjadwal ikut diperbarui; histori selesai tetap memakai Coach lama.</Text><ChoiceList label="Coach baru" options={coaches.map((coach) => ({ value: coach.user_id, label: coach.display_name }))} value={coachId} onChange={setCoachId} /><Field label="Alasan perubahan Coach" value={coachReason} onChangeText={setCoachReason} /><Button label="Ubah Coach" disabled={!coachId || coachId === person.current_coach_id || coachReason.trim().length < 8} loading={mutation.isPending} onPress={() => void execute({ kind: 'transferCoach', participantId: person.user_id, coachId, reason: coachReason })} /></Card>
      <Card><Text accessibilityRole="header" style={[styles.cardTitle, { color: colors.primaryText }]}>Penyesuaian poin</Text><ChoiceList label="Enrollment" options={(operations.data?.enrollments ?? []).map((enrollment) => ({ value: enrollment.id, label: enrollment.program_title }))} value={selectedEnrollment} onChange={setSelectedEnrollment} /><Field label="Jumlah poin" value={adjustment} inputMode="numeric" onChangeText={setAdjustment} message="Gunakan nilai negatif untuk pengurangan." /><Field label="Alasan penyesuaian" value={scoreReason} onChangeText={setScoreReason} /><Button label="Simpan penyesuaian" disabled={!selectedEnrollment || Number(adjustment) === 0 || scoreReason.trim().length < 8} loading={mutation.isPending} onPress={() => void execute({ kind: 'adjustScore', participantId: person.user_id, enrollmentId: selectedEnrollment, points: Number(adjustment), reason: scoreReason })} /></Card>
      {operations.data?.weighIns.length ? <Card><Text accessibilityRole="header" style={[styles.cardTitle, { color: colors.primaryText }]}>Riwayat berat badan privat</Text>{operations.data.weighIns.map((weighIn) => <View key={weighIn.id} style={styles.rowBetween}><Text style={[styles.body, { color: colors.primaryText }]}>{weighIn.kind} · {formatDateTime(weighIn.recorded_at)}</Text><Text style={[styles.numeric, { color: colors.primaryText }]}>{new Intl.NumberFormat('id-ID', { maximumFractionDigits: 1 }).format(weighIn.weight_kg)} kg</Text></View>)}</Card> : null}</> : null}
    {mutation.error instanceof Error ? <InlineMessage title="Operasi belum selesai" message={mutation.error.message} tone="destructive" /> : null}
  </ScrollView>;
}

function ChoiceList({ label, options, value, onChange }: { label: string; options: { value: string; label: string }[]; value: string; onChange: (value: string) => void }) { const { colors } = useAppTheme(); return <View style={styles.stack}><Text style={[styles.label, { color: colors.primaryText }]}>{label}</Text>{options.map((option) => <Pressable key={option.value} accessibilityRole="radio" accessibilityState={{ checked: value === option.value }} onPress={() => onChange(option.value)} style={[styles.choice, { borderColor: value === option.value ? colors.primaryAction : colors.border, backgroundColor: colors.surface }]}><Text style={[styles.body, { color: colors.primaryText }]}>{value === option.value ? '● ' : '○ '}{option.label}</Text></Pressable>)}</View>; }
function Detail({ label, value }: { label: string; value: string }) { const { colors } = useAppTheme(); return <View style={styles.detailRow}><Text style={[styles.caption, { color: colors.secondaryText }]}>{label}</Text><Text selectable style={[styles.bodyStrong, { color: colors.primaryText }]}>{value}</Text></View>; }
function roleLabel(role: AdminPerson['role']) { return ({ participant: 'Peserta', coach: 'Coach', admin: 'Admin' })[role]; }
function isPeopleScope(value: string): value is PeopleScope { return ['participant', 'coach', 'admin'].includes(value); }
function formatDateTime(value: string) { return new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Makassar' }).format(new Date(value)); }

const styles = StyleSheet.create({
  fixedScreen: { flex: 1, minHeight: 0 }, fixedControls: { borderBottomWidth: StyleSheet.hairlineWidth, padding: primitiveTokens.space.medium, gap: primitiveTokens.space.small }, searchField: { minHeight: componentTokens.inputHeight, flexDirection: 'row', alignItems: 'center', gap: primitiveTokens.space.small, borderWidth: 1, borderRadius: primitiveTokens.radius.medium, paddingHorizontal: primitiveTokens.space.medium }, searchInput: { flex: 1, minWidth: 0, ...typographyTokens.body }, peopleList: { width: '100%', maxWidth: componentTokens.contentMaxWidth, alignSelf: 'center', padding: primitiveTokens.space.medium, paddingBottom: 140, gap: primitiveTokens.space.medium },
  personRow: { minHeight: 72, flexDirection: 'row', alignItems: 'center', gap: primitiveTokens.space.medium, borderTopWidth: StyleSheet.hairlineWidth, paddingVertical: primitiveTokens.space.small }, inlineWrap: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: primitiveTokens.space.xSmall }, flex: { flex: 1, minWidth: 0 },
  detailContent: { width: '100%', maxWidth: componentTokens.contentMaxWidth, alignSelf: 'center', padding: primitiveTokens.space.medium, paddingBottom: 140, gap: primitiveTokens.space.medium }, identity: { flexDirection: 'row', alignItems: 'center', gap: primitiveTokens.space.medium }, detailRow: { gap: primitiveTokens.space.xxSmall }, enrollment: { borderTopWidth: StyleSheet.hairlineWidth, paddingTop: primitiveTokens.space.small, gap: primitiveTokens.space.small }, rowBetween: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: primitiveTokens.space.small }, stack: { gap: primitiveTokens.space.small }, choice: { minHeight: 48, borderWidth: 1, borderRadius: primitiveTokens.radius.medium, padding: primitiveTokens.space.small, justifyContent: 'center' },
  title: typographyTokens.title, sectionTitle: typographyTokens.title, cardTitle: typographyTokens.headline, body: typographyTokens.body, bodyStrong: typographyTokens.bodyStrong, caption: typographyTokens.caption, label: typographyTokens.label, numeric: { ...typographyTokens.bodyStrong, fontVariant: ['tabular-nums'] },
});
