import { useState } from 'react';
import { Image, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

import { componentTokens, primitiveTokens, typographyTokens } from '@/shared/design/tokens';
import { useAppTheme } from '@/shared/design/useAppTheme';
import { MSCIcon } from '@/shared/icons/MSCIcon';
import { Button, Card, Dialog, Field, InlineMessage, SegmentedControl, StateView, StatusBadge } from '@/shared/ui/primitives';
import type { AdminFoodOperation, AdminModerationItem, AdminPoster } from './admin-models';
import { useAdminFoodOperations, useAdminModeration, useAdminMutation, useAdminPosters, useAdminPrograms, useAdminWinnerSnapshots } from './admin-queries';
import { getAdminRepository } from './admin-repository';

type ContentScope = 'posters' | 'moderation' | 'ai';

export function AdminContentExperience({ authorized, initialScope = 'posters', createPoster = false }: { authorized: boolean; initialScope?: string; createPoster?: boolean }) {
  const { colors } = useAppTheme(); const [scope, setScope] = useState<ContentScope>(isScope(initialScope) ? initialScope : 'posters'); const [posterEditor, setPosterEditor] = useState(createPoster);
  if (!authorized) return <StateView kind="forbidden" />;
  return <View style={styles.fixedScreen} testID="admin.content"><View style={[styles.fixedControls, { backgroundColor: colors.background, borderColor: colors.border }]}><SegmentedControl label="Jenis konten Admin" value={scope} onChange={setScope} options={[{ label: 'Poster', value: 'posters' }, { label: 'Moderasi', value: 'moderation' }, { label: 'Insight AI', value: 'ai' }]} />{scope === 'posters' ? <Pressable accessibilityRole="button" accessibilityLabel="Poster pemenang, tambahkan gambar vertikal untuk galeri Home" onPress={() => setPosterEditor(true)} style={[styles.createRow, { backgroundColor: colors.surface, borderColor: colors.border }]} testID="admin.content.create-banner"><View style={[styles.createIcon, { backgroundColor: colors.primaryTintSurface }]}><MSCIcon name="image" color={colors.primaryAction} /></View><View style={styles.flex}><Text style={[styles.cardTitle, { color: colors.primaryText }]}>Poster pemenang</Text><Text style={[styles.caption, { color: colors.secondaryText }]}>Tambahkan gambar vertikal untuk galeri Home.</Text></View><View style={[styles.plus, { backgroundColor: colors.primaryAction }]}><MSCIcon name="plus" size="small" color={primitiveTokens.color.white} /></View></Pressable> : null}</View>
    {scope === 'posters' ? <PosterGallery editorVisible={posterEditor} onEditorOpen={() => setPosterEditor(true)} onEditorClose={() => setPosterEditor(false)} /> : scope === 'moderation' ? <ModerationQueue /> : <FoodOperations />}
  </View>;
}

function PosterGallery({ editorVisible, onEditorOpen, onEditorClose }: { editorVisible: boolean; onEditorOpen: () => void; onEditorClose: () => void }) {
  const { colors } = useAppTheme(); const posters = useAdminPosters(); const programs = useAdminPrograms(); const snapshots = useAdminWinnerSnapshots(); const mutation = useAdminMutation(); const [remove, setRemove] = useState<AdminPoster>(); const [reason, setReason] = useState('Poster dihapus dari galeri setelah peninjauan Admin.');
  if (posters.isPending || programs.isPending || snapshots.isPending) return <StateView kind="loading" />;
  if (posters.isError || programs.isError || snapshots.isError) return <StateView kind="error" action={<Button label="Coba lagi" onPress={() => void Promise.all([posters.refetch(), programs.refetch(), snapshots.refetch()])} />} />;
  return <ScrollView contentContainerStyle={styles.content}><Text accessibilityRole="header" style={[styles.sectionTitle, { color: colors.primaryText }]}>Poster pemenang</Text><Text style={[styles.body, { color: colors.secondaryText }]}>Ketuk tindakan poster untuk mengganti atau menghapusnya dari galeri.</Text>{posters.data?.length ? <View style={styles.posterGrid} testID="admin.content.poster-gallery">{posters.data.map((poster, index) => <View key={poster.id} style={styles.posterCell}><Image accessibilityLabel={poster.alt_text} source={{ uri: getAdminRepository().publicMediaUrl(poster.media_path) }} resizeMode="cover" style={[styles.posterImage, { backgroundColor: colors.secondaryBackground }]} /><View style={styles.posterOverlay}><View style={[styles.orderBadge, { backgroundColor: colors.surface }]}><Text style={[styles.label, { color: colors.primaryText }]}>{index + 1}</Text></View><Button label={`Hapus poster urutan ${index + 1}`} tone="secondary" icon="more" onPress={() => setRemove(poster)} /></View></View>)}</View> : <StateView kind="empty" action={<Button label="Tambah poster pertama" onPress={onEditorOpen} />} />}
    <PosterEditor visible={editorVisible} programs={programs.data ?? []} snapshots={snapshots.data ?? []} onClose={onEditorClose} />
    <Dialog visible={remove !== undefined} title="Hapus poster dari galeri?" onClose={() => setRemove(undefined)}><Field label="Alasan" value={reason} onChangeText={setReason} multiline /><Button label="Batal" tone="secondary" onPress={() => setRemove(undefined)} /><Button label="Hapus dari galeri" tone="destructive" disabled={reason.trim().length < 8} loading={mutation.isPending} onPress={() => remove && void mutation.mutateAsync({ kind: 'archivePoster', posterId: remove.id, reason }).then(() => setRemove(undefined))} /></Dialog>
  </ScrollView>;
}

function PosterEditor({ visible, programs, snapshots, onClose }: { visible: boolean; programs: { id: string; title: string; status: string }[]; snapshots: { id: string; program_id: string }[]; onClose: () => void }) {
  const { colors } = useAppTheme(); const mutation = useAdminMutation(); const [programId, setProgramId] = useState(''); const [file, setFile] = useState<File>(); const [altText, setAltText] = useState('Poster pemenang program.'); const [preview, setPreview] = useState<string>(); const [uploading, setUploading] = useState(false);
  const selectPoster = (next?: File) => { if (preview) URL.revokeObjectURL(preview); setFile(next); setPreview(next ? URL.createObjectURL(next) : undefined); };
  const completed = programs.filter((program) => ['completed', 'archived'].includes(program.status) && snapshots.some((snapshot) => snapshot.program_id === program.id)); const snapshot = snapshots.find((item) => item.program_id === programId);
  const close = () => { selectPoster(undefined); setProgramId(''); onClose(); };
  const save = async () => { if (!file || !snapshot) return; setUploading(true); try { const path = await getAdminRepository().uploadPublicImage(file, 'winners'); await mutation.mutateAsync({ kind: 'publishPoster', programId, snapshotId: snapshot.id, mediaPath: path, altText }); close(); } finally { setUploading(false); } };
  return <Dialog visible={visible} title="Poster pemenang" onClose={close}><ChoiceRows options={completed.map((program) => ({ value: program.id, label: program.title }))} value={programId} onChange={setProgramId} />{preview ? <Image accessibilityLabel="Pratinjau poster pemenang" source={{ uri: preview }} resizeMode="contain" style={[styles.posterPreview, { backgroundColor: colors.secondaryBackground }]} /> : <InlineMessage title="Poster wajib dipilih" message="Gunakan gambar vertikal rasio 9:16 dari perangkat." tone="warning" />}{Platform.OS === 'web' ? <label style={{ display: 'block' }}><span style={fileButtonStyle(colors.primaryAction)}>{file ? 'Ganti poster dari perangkat' : 'Pilih poster dari perangkat'}</span><input aria-label="Pilih poster pemenang" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" onChange={(event) => selectPoster(event.currentTarget.files?.[0])} style={hiddenFileInput} /></label> : null}<Field label="Teks alternatif" value={altText} onChangeText={setAltText} /><Button label="Batal" tone="secondary" onPress={close} /><Button label="Simpan poster" disabled={!programId || !file || altText.trim().length < 8} loading={uploading || mutation.isPending} onPress={() => void save()} testID="admin.content.save-banner" />{mutation.error instanceof Error ? <InlineMessage title="Poster belum disimpan" message={mutation.error.message} tone="destructive" /> : null}</Dialog>;
}

function ModerationQueue() {
  const { colors } = useAppTheme(); const queue = useAdminModeration();
  if (queue.isPending) return <StateView kind="loading" />;
  if (queue.isError) return <StateView kind="error" action={<Button label="Coba lagi" onPress={() => void queue.refetch()} />} />;
  return <ScrollView contentContainerStyle={styles.content}><Text accessibilityRole="header" style={[styles.sectionTitle, { color: colors.primaryText }]}>Moderasi profil Coach</Text><Text style={[styles.body, { color: colors.secondaryText }]}>Testimoni dan sebelum–sesudah hanya terbit setelah keputusan Admin.</Text>{queue.data?.length ? queue.data.map((item) => <ModerationCard key={item.id} item={item} />) : <StateView kind="empty" />}</ScrollView>;
}

function ModerationCard({ item }: { item: AdminModerationItem }) {
  const { colors } = useAppTheme(); const mutation = useAdminMutation(); const [mode, setMode] = useState<'idle' | 'approve' | 'reject'>('idle'); const [note, setNote] = useState('');
  return <View testID={`admin.moderation.item.${item.id}`}><Card><View style={styles.rowBetween}><View style={styles.flex}><Text style={[styles.cardTitle, { color: colors.primaryText }]}>{item.title}</Text><Text style={[styles.caption, { color: colors.secondaryText }]}>{item.coach_name} · {item.item_kind === 'testimonial' ? 'Testimoni' : 'Sebelum–sesudah'} · versi {item.content_version}</Text></View><StatusBadge label={moderationLabel(item.moderation_status)} tone={item.moderation_status === 'approved' ? 'success' : item.moderation_status === 'rejected' ? 'destructive' : 'warning'} /></View><Text style={[styles.body, { color: colors.primaryText }]}>{item.body}</Text>{item.media_object_path ? <Image accessibilityLabel={`Media moderasi ${item.title}`} source={{ uri: getAdminRepository().coachMediaUrl(item.media_object_path) }} resizeMode="contain" style={[styles.moderationMedia, { backgroundColor: colors.secondaryBackground }]} /> : null}<Text style={[styles.caption, { color: colors.secondaryText }]}>Pihak lain: {item.includes_third_party ? 'Ya' : 'Tidak'} · Izin: {item.includes_third_party ? item.permission_attested ? 'Dinyatakan ada' : 'Belum ada' : 'Tidak diperlukan'}</Text>{mode !== 'idle' ? <><Field label={mode === 'reject' ? 'Alasan penolakan' : 'Catatan keputusan (opsional)'} value={note} onChangeText={setNote} multiline /><View style={styles.actionRow}><Button label="Batal" tone="secondary" onPress={() => setMode('idle')} /><Button label={mode === 'reject' ? 'Tolak konten' : 'Setujui konten'} tone={mode === 'reject' ? 'destructive' : 'primary'} disabled={mode === 'reject' && note.trim().length < 8} loading={mutation.isPending} onPress={() => void mutation.mutateAsync({ kind: 'moderate', item, decision: mode === 'reject' ? 'rejected' : 'approved', note }).then(() => setMode('idle'))} /></View></> : item.moderation_status === 'pending' ? <View style={styles.actionRow}><Button label="Tolak" tone="destructive" onPress={() => setMode('reject')} /><Button label="Setujui" onPress={() => setMode('approve')} /></View> : item.moderation_note ? <InlineMessage title="Catatan pemeriksaan" message={item.moderation_note} tone={item.moderation_status === 'rejected' ? 'destructive' : 'info'} /> : null}{mutation.error instanceof Error ? <InlineMessage title="Keputusan belum disimpan" message={mutation.error.message} tone="destructive" /> : null}</Card></View>;
}

function FoodOperations() {
  const { colors } = useAppTheme(); const queue = useAdminFoodOperations();
  if (queue.isPending) return <StateView kind="loading" />;
  if (queue.isError) return <StateView kind="error" action={<Button label="Coba lagi" onPress={() => void queue.refetch()} />} />;
  return <ScrollView contentContainerStyle={styles.content}><Text accessibilityRole="header" style={[styles.sectionTitle, { color: colors.primaryText }]}>Operasional insight AI</Text><InlineMessage title="Data sensitif disamarkan" message="Halaman ini tidak menampilkan API key, prompt, response provider, signed URL, atau path media privat." />{queue.data?.length ? queue.data.map((item) => <FoodOperationCard key={item.job_id} operation={item} />) : <StateView kind="empty" />}</ScrollView>;
}

function FoodOperationCard({ operation }: { operation: AdminFoodOperation }) {
  const { colors } = useAppTheme(); const mutation = useAdminMutation(); const [open, setOpen] = useState(false); const [rating, setRating] = useState(operation.effective_rating ?? 4); const [reason, setReason] = useState(''); const failure = ['failed', 'unavailable'].includes(operation.status);
  return <Card><View style={styles.rowBetween}><View style={styles.flex}><Text style={[styles.cardTitle, { color: colors.primaryText }]}>{operation.participant_name}</Text><Text style={[styles.body, { color: colors.secondaryText }]}>{operation.program_title} · {operation.step_title}</Text></View><StatusBadge label={aiStatusLabel(operation.status)} tone={failure ? 'destructive' : operation.status === 'completed' ? 'success' : 'warning'} /></View><View style={styles.metaGrid}><Meta label="Versi analisis" value={operation.analysis_version} /><Meta label="Provider" value={operation.provider_name ?? 'Belum ada'} /><Meta label="Model" value={operation.model_alias ?? 'Belum ada'} /><Meta label="Percobaan" value={`${operation.attempt_count}/${operation.max_attempts}`} /><Meta label="Error" value={operation.terminal_error_code ?? '—'} /></View>{operation.effective_rating ? <Text accessibilityLabel={`${operation.effective_rating} dari 5 bintang`} style={[styles.bodyStrong, { color: colors.primaryText }]}>Rating efektif: {operation.effective_rating}/5</Text> : null}{operation.result_id ? open ? <><View style={styles.ratingRow}>{[1, 2, 3, 4, 5].map((value) => <Pressable key={value} accessibilityRole="button" accessibilityLabel={`${value} dari 5 bintang`} onPress={() => setRating(value)} style={styles.ratingButton}><MSCIcon name="star" color={value <= rating ? colors.accent : colors.border} weight={value <= rating ? 'fill' : 'regular'} /></Pressable>)}</View><Field label="Alasan koreksi rating AI" value={reason} onChangeText={setReason} multiline /><View style={styles.actionRow}><Button label="Batal" tone="secondary" onPress={() => setOpen(false)} /><Button label="Simpan koreksi" disabled={reason.trim().length < 8} loading={mutation.isPending} onPress={() => void mutation.mutateAsync({ kind: 'correctFood', operation, rating, reason }).then(() => setOpen(false))} /></View></> : <Button label="Koreksi rating AI" tone="secondary" onPress={() => setOpen(true)} /> : null}{mutation.error instanceof Error ? <InlineMessage title="Koreksi belum disimpan" message={mutation.error.message} tone="destructive" /> : null}</Card>;
}

function ChoiceRows({ options, value, onChange }: { options: { value: string; label: string }[]; value: string; onChange: (value: string) => void }) { const { colors } = useAppTheme(); return <View style={styles.stack}>{options.map((option) => <Pressable key={option.value} accessibilityRole="radio" accessibilityState={{ checked: value === option.value }} onPress={() => onChange(option.value)} style={[styles.choice, { borderColor: value === option.value ? colors.primaryAction : colors.border }]}><Text style={[styles.body, { color: colors.primaryText }]}>{value === option.value ? '● ' : '○ '}{option.label}</Text></Pressable>)}</View>; }
function Meta({ label, value }: { label: string; value: string }) { const { colors } = useAppTheme(); return <View style={styles.meta}><Text style={[styles.caption, { color: colors.secondaryText }]}>{label}</Text><Text style={[styles.bodyStrong, { color: colors.primaryText }]}>{value}</Text></View>; }
function moderationLabel(status: string) { return ({ pending: 'Menunggu', approved: 'Disetujui', rejected: 'Ditolak' } as Record<string, string>)[status] ?? status; }
function aiStatusLabel(status: string) { return ({ queued: 'Mengantre', processing: 'Diproses', retry_scheduled: 'Dijadwalkan ulang', completed: 'Selesai', failed: 'Gagal', unavailable: 'Tidak tersedia' } as Record<string, string>)[status] ?? status; }
function isScope(value: string): value is ContentScope { return ['posters', 'moderation', 'ai'].includes(value); }

const hiddenFileInput = { position: 'absolute', width: 1, height: 1, overflow: 'hidden', clip: 'rect(0, 0, 0, 0)', whiteSpace: 'nowrap' } as const;
function fileButtonStyle(backgroundColor: string) { return { alignItems: 'center', backgroundColor, borderRadius: 12, color: primitiveTokens.color.white, cursor: 'pointer', display: 'flex', fontSize: 16, fontWeight: 700, justifyContent: 'center', minHeight: 48, padding: '12px 16px' } as const; }

const styles = StyleSheet.create({
  fixedScreen: { flex: 1, minHeight: 0 }, fixedControls: { borderBottomWidth: StyleSheet.hairlineWidth, padding: primitiveTokens.space.medium, gap: primitiveTokens.space.small }, createRow: { minHeight: 76, flexDirection: 'row', alignItems: 'center', gap: primitiveTokens.space.small, borderWidth: 1, borderRadius: primitiveTokens.radius.large, padding: primitiveTokens.space.small }, createIcon: { width: 48, height: 48, borderRadius: primitiveTokens.radius.medium, alignItems: 'center', justifyContent: 'center' }, plus: { width: 30, height: 30, borderRadius: 15, alignItems: 'center', justifyContent: 'center' },
  content: { width: '100%', maxWidth: componentTokens.contentMaxWidth, alignSelf: 'center', padding: primitiveTokens.space.medium, paddingBottom: 140, gap: primitiveTokens.space.medium }, posterGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: primitiveTokens.space.small }, posterCell: { flexGrow: 1, flexBasis: '46%', maxWidth: 360, minWidth: 140, aspectRatio: 9 / 16 }, posterImage: { width: '100%', height: '100%', borderRadius: primitiveTokens.radius.large }, posterOverlay: { position: 'absolute', left: primitiveTokens.space.xSmall, right: primitiveTokens.space.xSmall, top: primitiveTokens.space.xSmall, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, orderBadge: { minWidth: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, posterPreview: { width: '100%', maxWidth: 320, alignSelf: 'center', aspectRatio: 9 / 16, borderRadius: primitiveTokens.radius.large },
  moderationMedia: { width: '100%', height: 280, borderRadius: primitiveTokens.radius.large }, rowBetween: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'flex-start', justifyContent: 'space-between', gap: primitiveTokens.space.small }, actionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: primitiveTokens.space.small }, flex: { flex: 1, minWidth: 0 }, stack: { gap: primitiveTokens.space.small }, choice: { minHeight: 48, borderWidth: 1, borderRadius: primitiveTokens.radius.medium, padding: primitiveTokens.space.small, justifyContent: 'center' }, metaGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: primitiveTokens.space.small }, meta: { minWidth: 140, flex: 1, gap: primitiveTokens.space.xxSmall }, ratingRow: { flexDirection: 'row', gap: primitiveTokens.space.xxSmall }, ratingButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  sectionTitle: typographyTokens.title, cardTitle: typographyTokens.headline, body: typographyTokens.body, bodyStrong: typographyTokens.bodyStrong, caption: typographyTokens.caption, label: typographyTokens.label,
});
